#!/bin/sh

echo
echo Запущен скрипт остановки ZRAM
echo [Процесс может занять некоторое время]

swapoff \/dev\/block\/zram* > \/dev\/null 2>&1
echo '1' > \/sys\/block\/zram*\/reset
echo '0' > \/sys\/block\/zram*\/disksize
sleep 2

echo
echo Остановка ZRAM выполнена. Вывод состояния памяти "(Строка Swap должна содержать 0)"
echo
free

echo
echo Команда для настройки ZRAM [zramconf]
echo Команда для оптимального запуска ZRAM [zramauto]
echo
